model = dict(
    type='DBNet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        stage_with_dcn=(False, True, True, True)),
    neck=dict(
        type='FPNC',
        in_channels=[256, 512, 1024, 2048],
        lateral_channels=256,
        asf_cfg=dict(attention_type='ScaleChannelSpatial')),
    det_head=dict(
        type='PANSegHistHead',
        in_channels=256,  
        num_blocks=3,
        num_query=8,
        output_channels=7,
        shallow_channels=128,
        embedding_channels=128, # = shallow channels
        use_dyrelu=True,
        dyrelu_mode='awared',
        with_m2f_mask=True,
        module_loss=dict(type='PSETKSModuleLoss',
                         shrink_ratio=(1, 0.8, 0.6, 0.4, 0.2, 0, -0.2),
                         stretch_ratio=2),
        postprocessor=dict(type='PSEPostprocessor', 
                           text_repr_type='poly',
                           min_text_area=200,
                           score_threshold=0.6,
                           downsample_ratio=1)),
    data_preprocessor=dict(
        type='TextDetDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_size_divisor=32))
